name: multi-omics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.3.0
  - numpy>=1.21.0
  - scikit-learn>=1.0.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - networkx>=2.6.0
  - pip
  - pip:
    - # 如有其他pip专用包可在此添加